<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
    <Version>1.4.0</Version>
    <PackageId></PackageId>
    <Authors>phone2345</Authors>
    <Product>VRCScalerOSC</Product>
    <Copyright>Copyright © 2026 phone2345. All Rights Reserved.</Copyright>
    <Nullable>enable</Nullable>
    <ApplicationIcon>VRCScalerOSC.ico</ApplicationIcon>
    <PackageIcon>VRCScalerOSC.png</PackageIcon>
    
    <!-- Single File and Ready to Run Settings -->
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    
    <!-- Exclude PDB files -->
    <DebugType>embedded</DebugType>
    <PublishDebugSymbols>false</PublishDebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="VRCScalerOSC.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VRCScalerOSC\VRCScalerOSC.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="View\ScalerForm.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="VRCScalerOSC.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>